
const MOCK_SERVICES = [
  {
    id: 'svc_hair_anna',
    category: 'hair',
    name_ru: 'Студия красоты Анны',
    name_en: 'Anna Hair Studio',
    name_vi: 'Anna Hair Studio',
    name_ko: '안나 헤어 스튜디오',
    name_es: 'Anna Hair Studio',
    name_zh: '安娜美发工作室',
    name_fr: 'Anna Hair Studio',
    desc_ru: 'Лучший мастер по колористике и стрижкам в городе.',
    desc_en: 'Best coloring and haircut master in the city.',
    desc_vi: 'Thợ nhuộm và cắt tóc giỏi nhất thành phố.',
    desc_ko: '시내 최고의 컬러링 및 헤어컷 마스터.',
    desc_es: 'La mejor maestra de coloración y corte de pelo.',
    desc_zh: '全市最好的染发和理发大师。',
    desc_fr: 'Meilleur maître de coloration et de coupe de cheveux.',
    all_tags: 'tag_area_center; tag_search_haircut; tag_search_coloring; tag_search_blond',
    ext_5: 'online_booking; vn_speaking',
    ext_6: 'Скидка 10% на первое посещение!',
    ig_link: '@anna_hair',
    tg_link: '@anna_booking',
    price_level: 'budget'
  },
  {
    id: 'svc_massage_dr',
    category: 'health',
    name_ru: 'Dr. Massage (Слепые мастера)',
    name_en: 'Dr. Massage (Blind masters)',
    name_vi: 'Massage Khiếm thị Dr. Massage',
    name_ko: 'Dr. Massage (시각장애인 마사지)',
    name_es: 'Dr. Massage (Masaje a ciegas)',
    name_zh: 'Dr. Massage (盲人按摩)',
    name_fr: 'Dr. Massage (Masseurs aveugles)',
    desc_ru: 'Традиционный лечебный массаж от профессионалов.',
    desc_en: 'Traditional therapeutic massage from professionals.',
    desc_vi: 'Massage trị liệu truyền thống từ các chuyên gia.',
    desc_ko: '전문가의 전통 치료 마사지.',
    desc_es: 'Masaje terapéutico tradicional.',
    desc_zh: '专业人士的传统治疗按摩。',
    desc_fr: 'Massage thérapeutique traditionnel par des professionnels.',
    all_tags: 'tag_area_south; tag_search_massage; tag_search_chiropractor',
    ext_5: 'cash_only; walk_ins_welcome',
    ext_6: 'Счастливые часы с 10:00 до 12:00',
    ig_link: '',
    tg_link: 't.me/drmassage',
    price_level: 'budget'
  },
  {
    id: 'svc_fitness_alex',
    category: 'fitness',
    name_ru: 'Персональный Тренер Алекс',
    name_en: 'Alex Personal Trainer',
    name_vi: 'Huấn luyện viên cá nhân Alex',
    name_ko: '알렉스 개인 트레이너',
    name_es: 'Entrenador Personal Alex',
    name_zh: 'Alex私人教练',
    name_fr: 'Coach Personnel Alex',
    desc_ru: 'Составление плана питания и тренировки.',
    desc_en: 'Nutrition and training plan preparation.',
    desc_vi: 'Chuẩn bị kế hoạch dinh dưỡng và đào tạo.',
    desc_ko: '영양 및 훈련 계획 준비.',
    desc_es: 'Preparación de plan de nutrición y entrenamiento.',
    desc_zh: '营养和培训计划准备。',
    desc_fr: 'Préparation du plan de nutrition et d\'entraînement.',
    all_tags: 'tag_area_north; tag_search_fitness_trainer; tag_search_personal_trainer; tag_search_gym',
    ext_5: 'free_consult; ru_speaking',
    ext_6: '',
    ig_link: '@alex_fit',
    tg_link: '@alex_train',
    price_level: 'mid'
  },
  {
    id: 'svc_clean_house',
    category: 'home_services',
    name_ru: 'Клининг 24/7',
    name_en: 'Cleaning 24/7',
    name_vi: 'Dọn dẹp 24/7',
    name_ko: '청소 24/7',
    name_es: 'Limpieza 24/7',
    name_zh: '清洁 24/7',
    name_fr: 'Nettoyage 24/7',
    desc_ru: 'Быстрая уборка квартир и вилл после выселения.',
    desc_en: 'Fast cleaning of apartments and villas after eviction.',
    desc_vi: 'Dọn dẹp nhanh chóng các căn hộ và biệt thự.',
    desc_ko: '아파트 및 빌라의 빠른 청소.',
    desc_es: 'Limpieza rápida de apartamentos y villas.',
    desc_zh: '快速清洁公寓和别墅。',
    desc_fr: 'Nettoyage rapide d\'appartements et de villas.',
    all_tags: 'tag_area_north; tag_area_center; tag_area_south; tag_search_cleaning; tag_search_house_cleaning',
    ext_5: 'urgent_service; vn_speaking',
    ext_6: 'Бесплатная мойка окон!',
    ig_link: '',
    tg_link: 'zalo.me/cleaning247',
    price_level: 'budget'
  },
  {
    id: 'svc_visa_express',
    category: 'legal_visa',
    name_ru: 'Визовый Центр Express',
    name_en: 'Visa Express Center',
    name_vi: 'Trung tâm Visa Express',
    name_ko: '비자 익스프레스 센터',
    name_es: 'Centro Visa Express',
    name_zh: 'Visa Express 中心',
    name_fr: 'Centre Visa Express',
    desc_ru: 'Помощь с ВНЖ, продлением визы и бордерранами.',
    desc_en: 'Help with TRC, visa extension and border runs.',
    desc_vi: 'Trợ giúp làm thẻ tạm trú, gia hạn visa và border run.',
    desc_ko: 'TRC, 비자 연장 및 보더 런 도움말.',
    desc_es: 'Ayuda con permisos de residencia y visados.',
    desc_zh: '协助办理居住证和签证。',
    desc_fr: 'Aide pour le permis de séjour et les visas.',
    all_tags: 'tag_area_center; tag_search_visarun; tag_search_borderrun; tag_search_residence_permit',
    ext_5: 'online_booking; guarantee',
    ext_6: '',
    ig_link: '@visa_express',
    tg_link: 't.me/visa_exp',
    price_level: 'premium'
  },
  {
    id: 'svc_english_mary',
    category: 'education',
    name_ru: 'Английский с Мэри',
    name_en: 'English with Mary',
    name_vi: 'Tiếng Anh cùng Mary',
    name_ko: '메리와 함께하는 영어',
    name_es: 'Inglés con Mary',
    name_zh: '和玛丽学英语',
    name_fr: 'Anglais avec Mary',
    desc_ru: 'Репетитор для детей и взрослых. Разговорный клуб.',
    desc_en: 'Tutor for kids and adults. Speaking club.',
    desc_vi: 'Gia sư cho trẻ em và người lớn. Câu lạc bộ nói.',
    desc_ko: '어린이 및 성인용 튜터. 스피킹 클럽.',
    desc_es: 'Tutor para niños y adultos. Club de conversación.',
    desc_zh: '成人和儿童的导师。口语俱乐部。',
    desc_fr: 'Tuteur pour enfants et adultes. Club de discussion.',
    all_tags: 'tag_area_north; tag_search_tutor; tag_search_english',
    ext_5: 'online_booking; eng_speaking',
    ext_6: 'Первый урок бесплатно',
    ig_link: '@mary_eng',
    tg_link: '@mary_teach',
    price_level: 'mid'
  },
  {
    id: 'svc_moto_repair',
    category: 'auto_moto',
    name_ru: 'Ремонт байков 24/7',
    name_en: 'Moto Repair 24/7',
    name_vi: 'Sửa xe máy 24/7',
    name_ko: '오토바이 수리 24/7',
    name_es: 'Reparación de motos 24/7',
    name_zh: '摩托车修理 24/7',
    name_fr: 'Réparation de moto 24/7',
    desc_ru: 'Срочный выезд мастера по всему Нячангу. Замена масла.',
    desc_en: 'Urgent mechanic departure across Nha Trang. Oil change.',
    desc_vi: 'Sửa xe khẩn cấp khắp Nha Trang. Thay dầu.',
    desc_ko: '나짱 전역 긴급 수리. 오일 교환.',
    desc_es: 'Salida mecánica urgente. Cambio de aceite.',
    desc_zh: '芽庄各地紧急修理。换油。',
    desc_fr: 'Départ mécanique urgent. Vidange.',
    all_tags: 'tag_area_north; tag_area_center; tag_area_south; tag_search_bike_rental',
    ext_5: 'urgent_service; home_visit; vn_speaking',
    ext_6: '',
    ig_link: '',
    tg_link: '+84123456789',
    price_level: 'budget'
  },
  {
    id: 'svc_surf_school',
    category: 'fitness',
    name_ru: 'Школа Серфинга',
    name_en: 'Nha Trang Surf School',
    name_vi: 'Trường lướt sóng Nha Trang',
    name_ko: '나짱 서핑 스쿨',
    name_es: 'Escuela de Surf',
    name_zh: '芽庄冲浪学校',
    name_fr: 'École de Surf',
    desc_ru: 'Ловим волны каждый день на Бай Зай!',
    desc_en: 'Catch waves every day at Bai Dai!',
    desc_vi: 'Bắt sóng mỗi ngày tại Bãi Dài!',
    desc_ko: '매일 파도를 타세요!',
    desc_es: '¡Atrapa olas todos los días!',
    desc_zh: '每天都在冲浪！',
    desc_fr: 'Attrapez les vagues tous les jours !',
    all_tags: 'tag_area_south; tag_search_surfing',
    ext_5: 'eng_speaking; ru_speaking',
    ext_6: 'Скидка на групповые занятия',
    ig_link: '@surf_nt',
    tg_link: '@surf_nt',
    price_level: 'mid'
  },
  {
    id: 'svc_pet_grooming',
    category: 'pets',
    name_ru: 'Груминг "Пушистик"',
    name_en: 'Fluffy Pet Grooming',
    name_vi: 'Cắt tỉa lông thú cưng',
    name_ko: '플러피 애완동물 그루밍',
    name_es: 'Peluquería de mascotas',
    name_zh: '宠物美容',
    name_fr: 'Toilettage pour animaux',
    desc_ru: 'Стрижка кошек и собак без стресса.',
    desc_en: 'Stress-free dog and cat grooming.',
    desc_vi: 'Cắt tỉa lông chó mèo không căng thẳng.',
    desc_ko: '스트레스 없는 개와 고양이 그루밍.',
    desc_es: 'Peluquería de perros y gatos sin estrés.',
    desc_zh: '无压力的狗和猫美容。',
    desc_fr: 'Toilettage sans stress pour chiens et chats.',
    all_tags: 'tag_area_north; tag_search_grooming',
    ext_5: 'online_booking; portfolio_avail',
    ext_6: '',
    ig_link: '@fluffy_grooming',
    tg_link: '@fluffy_groom',
    price_level: 'premium'
  },
  {
    id: 'svc_flower_delivery',
    category: 'flowers',
    name_ru: 'Доставка букетов Rose',
    name_en: 'Rose Flower Delivery',
    name_vi: 'Giao hoa Rose',
    name_ko: '로즈 꽃 배달',
    name_es: 'Entrega de flores Rose',
    name_zh: 'Rose 鲜花派送',
    name_fr: 'Livraison de fleurs Rose',
    desc_ru: 'Свежие розы и авторские букеты с доставкой за час.',
    desc_en: 'Fresh roses and custom bouquets delivered in an hour.',
    desc_vi: 'Hoa hồng tươi và bó hoa tùy chỉnh giao trong một giờ.',
    desc_ko: '한 시간 내에 신선한 장미 배달.',
    desc_es: 'Rosas frescas entregadas en una hora.',
    desc_zh: '一小时内运送新鲜玫瑰。',
    desc_fr: 'Roses fraîches livrées en une heure.',
    all_tags: 'tag_area_north; tag_area_center; tag_area_south; tag_search_flower_delivery',
    ext_5: 'crypto_payment; online_booking',
    ext_6: 'Бесплатная доставка',
    ig_link: '@rose_flowers',
    tg_link: '@rose_flowers_bot',
    price_level: 'premium'
  }
];

const axios = require('axios');

async function addMocks() {
  for (const poi of MOCK_SERVICES) {
    try {
      const res = await axios.post('http://localhost:3001/api/pois?mode=services', poi);
      console.log(`Added ${poi.name_ru}: ${res.status}`);
    } catch (err) {
      console.error(`Error adding ${poi.name_ru}:`, err.response ? err.response.data : err.message);
    }
  }
}

addMocks();
