const DISCOUNT_CODES_I18N = {
  '100': { ru: 'Скидка на весь чек', en: 'Discount on full bill', vi: 'Giảm toàn bộ hóa đơn', ko: '전체 금액 할인', zh: '全单折扣', fr: 'Remise sur l\'addition', es: 'Descuento en total' },
  '1':   { ru: 'Только на напитки', en: 'Drinks only', vi: 'Chỉ đồ uống', ko: '음료만', zh: '仅饮品', fr: 'Boissons seulement', es: 'Solo bebidas' },
  '2':   { ru: 'Только на меню кухни', en: 'Food menu only', vi: 'Chỉ thực đơn', ko: '음식 메뉴만', zh: '仅餐食', fr: 'Menu cuisine seulement', es: 'Solo menú de comida' },
  '3':   { ru: 'Кроме алкоголя', en: 'Excluding alcohol', vi: 'Trừ rượu', ko: '주류 제외', zh: '不含酒精', fr: 'Hors alcool', es: 'Excepto alcohol' },
  '4':   { ru: 'Специальное предложение', en: 'Special offer', vi: 'Ưu đãi đặc biệt', ko: '특별 제공', zh: '特别优惠', fr: 'Offre spéciale', es: 'Oferta especial' },
  '5':   { ru: 'Happy Hour (14:00–17:00)', en: 'Happy Hour (14:00–17:00)', vi: 'Happy Hour (14:00–17:00)', ko: '해피아워 (14:00–17:00)', zh: '欢乐时光 14:00–17:00', fr: 'Happy Hour (14h–17h)', es: 'Happy Hour (14:00–17:00)' },
  '6':   { ru: 'Мин. чек 500k VND', en: 'Min. bill 500k VND', vi: 'Tối thiểu 500k VND', ko: '최소 500k VND', zh: '最低消费500k', fr: 'Commande min. 500k VND', es: 'Pedido mín. 500k VND' },
  '7':   { ru: 'Завтраки (08:00–10:00)', en: 'Breakfast (08:00–10:00)', vi: 'Bữa sáng (08:00–10:00)', ko: '조식 (08:00–10:00)', zh: '早餐 08:00–10:00', fr: 'Petit-déjeuner (08h–10h)', es: 'Desayuno (08:00–10:00)' },
  '8':   { ru: 'Завтраки (08:00–11:00)', en: 'Breakfast (08:00–11:00)', vi: 'Bữa sáng (08:00–11:00)', ko: '조식 (08:00–11:00)', zh: '早餐 08:00–11:00', fr: 'Petit-déjeuner (08h–11h)', es: 'Desayuno (08:00–11:00)' },
  '9':   { ru: 'Завтраки (08:00–12:00)', en: 'Breakfast (08:00–12:00)', vi: 'Bữa sáng (08:00–12:00)', ko: '조식 (08:00–12:00)', zh: '早餐 08:00–12:00', fr: 'Petit-déjeuner (08h–12h)', es: 'Desayuno (08:00–12:00)' },
  '10':  { ru: 'Вечер (17:00–19:00)', en: 'Evening (17:00–19:00)', vi: 'Buổi tối (17:00–19:00)', ko: '저녁 (17:00–19:00)', zh: '晚间 17:00–19:00', fr: 'Soir (17h–19h)', es: 'Noche (17:00–19:00)' },
  '11':  { ru: 'Вечер (17:00–20:00)', en: 'Evening (17:00–20:00)', vi: 'Buổi tối (17:00–20:00)', ko: '저녁 (17:00–20:00)', zh: '晚间 17:00–20:00', fr: 'Soir (17h–20h)', es: 'Noche (17:00–20:00)' },
  '12':  { ru: 'После 20:00', en: 'After 20:00', vi: 'Sau 20:00', ko: '20:00 이후', zh: '20:00后', fr: 'Après 20h', es: 'Después de las 20:00' },
  '13':  { ru: 'После 21:00', en: 'After 21:00', vi: 'Sau 21:00', ko: '21:00 이후', zh: '21:00后', fr: 'Après 21h', es: 'Después de las 21:00' },
  '14':  { ru: 'После 22:00', en: 'After 22:00', vi: 'Sau 22:00', ko: '22:00 이후', zh: '22:00后', fr: 'Après 22h', es: 'Después de las 22:00' },
  '15':  { ru: 'По будням (Пн–Пт)', en: 'Weekdays (Mon–Fri)', vi: 'Ngày thường (T2–T6)', ko: '평일 (월–금)', zh: '工作日 周一至五', fr: 'En semaine (Lun–Ven)', es: 'Entre semana (Lun–Vie)' },
  '16':  { ru: 'Компании от 4-х чел', en: 'Groups 4+ people', vi: 'Nhóm từ 4 người', ko: '4인 이상 그룹', zh: '4人以上团体', fr: 'Groupe de 4+', es: 'Grupos de 4+ personas' },
  '17':  { ru: 'День рождения (±3 дня)', en: 'Birthday (±3 days)', vi: 'Sinh nhật (±3 ngày)', ko: '생일 (±3일)', zh: '生日 (±3天)', fr: 'Anniversaire (±3 jours)', es: 'Cumpleaños (±3 días)' },
  '18':  { ru: 'Только для девушек', en: 'Ladies only', vi: 'Chỉ dành cho nữ', ko: '여성 전용', zh: '仅限女性', fr: 'Dames seulement', es: 'Solo para mujeres' },
  '19':  { ru: 'Для семей с детьми', en: 'Families with children', vi: 'Gia đình có trẻ em', ko: '어린이 동반 가족', zh: '带小孩家庭', fr: 'Familles avec enfants', es: 'Familias con niños' },
  '20':  { ru: 'За отзыв в Google Maps', en: 'For Google Maps review', vi: 'Khi đánh giá Google Maps', ko: '구글맵 리뷰 작성 시', zh: '谷歌地图评论', fr: 'Pour un avis Google Maps', es: 'Por reseña en Google Maps' },
  '21':  { ru: 'Только на вынос', en: 'Takeaway only', vi: 'Chỉ mang về', ko: '포장 전용', zh: '仅外卖', fr: 'À emporter seulement', es: 'Solo para llevar' },
  '22':  { ru: 'При оплате наличными', en: 'Cash payment', vi: 'Thanh toán tiền mặt', ko: '현금 결제 시', zh: '现金支付', fr: 'Paiement en espèces', es: 'Pago en efectivo' },
  '23':  { ru: 'Мин. чек 1 млн VND', en: 'Min. bill 1M VND', vi: 'Tối thiểu 1 triệu VND', ko: '최소 100만 VND', zh: '最低消费100万', fr: 'Commande min. 1M VND', es: 'Pedido mín. 1M VND' },
  '24':  { ru: 'На вьетнамскую кухню', en: 'Vietnamese cuisine', vi: 'Ẩm thực Việt Nam', ko: '베트남 요리', zh: '越南菜', fr: 'Cuisine vietnamienne', es: 'Cocina vietnamita' },
  '25':  { ru: 'Только на морепродукты', en: 'Seafood only', vi: 'Chỉ hải sản', ko: '해산물만', zh: '仅海鲜', fr: 'Fruits de mer seulement', es: 'Solo mariscos' },
  '26':  { ru: 'На первый заказ', en: 'First order', vi: 'Lần đầu đặt hàng', ko: '첫 주문', zh: '首单优惠', fr: 'Première commande', es: 'Primer pedido' },
  '27':  { ru: '1+1 (BOGO)', en: '1+1 (Buy One Get One)', vi: '1 tặng 1', ko: '1+1', zh: '买一送一', fr: '1+1 (Achetez-en 1, obtenez-en 1)', es: '1+1 (Lleva 2, paga 1)' },
  '28':  { ru: 'За пост в соцсетях', en: 'For social media post', vi: 'Đăng bài mạng xã hội', ko: 'SNS 게시물 작성 시', zh: '社交媒体发帖', fr: 'Pour une publication sur les réseaux', es: 'Por publicación en redes' },
  '29':  { ru: 'В дождливую погоду', en: 'Rainy weather', vi: 'Thời tiết mưa', ko: '우천 시', zh: '雨天优惠', fr: 'Par temps de pluie', es: 'Día lluvioso' },
  '30':  { ru: 'Для групп от 10 чел', en: 'Groups 10+ people', vi: 'Nhóm từ 10 người', ko: '10인 이상 그룹', zh: '10人以上团体', fr: 'Groupes de 10+', es: 'Grupos de 10+ personas' },
  '31':  { ru: 'Завтраки до 11:00', en: 'Breakfast until 11:00', vi: 'Bữa sáng đến 11:00', ko: '조식 11:00까지', zh: '早餐至11:00', fr: 'Petit-déjeuner jusqu\'à 11h', es: 'Desayuno hasta las 11:00' },
  '32':  { ru: 'После 22:00', en: 'After 22:00', vi: 'Sau 22:00', ko: '22:00 이후', zh: '22:00后', fr: 'Après 22h', es: 'Después de las 22:00' },
  '33':  { ru: 'Эксклюзивно в приложении', en: 'App exclusive', vi: 'Chỉ trong ứng dụng', ko: '앱 전용', zh: '应用专属', fr: 'Exclusif sur l\'appli', es: 'Exclusivo en la app' },
  '34':  { ru: 'Напиток в подарок', en: 'Free drink', vi: 'Tặng đồ uống', ko: '음료 무료 증정', zh: '赠饮品', fr: 'Boisson offerte', es: 'Bebida gratis' },
  '35':  { ru: 'Десерт в подарок', en: 'Free dessert', vi: 'Tặng tráng miệng', ko: '디저트 무료 증정', zh: '赠甜点', fr: 'Dessert offert', es: 'Postre gratis' },
  '36':  { ru: 'Только внутри заведения', en: 'Dine-in only', vi: 'Chỉ dùng tại chỗ', ko: '매장 내 식사만', zh: '仅堂食', fr: 'Sur place seulement', es: 'Solo en local' },
  '37':  { ru: 'От 3-х блюд', en: 'From 3 dishes', vi: 'Từ 3 món', ko: '3가지 이상 주문 시', zh: '3道菜起', fr: 'À partir de 3 plats', es: 'Desde 3 platos' },
  '38':  { ru: 'Только для резидентов', en: 'Residents only', vi: 'Chỉ cư dân', ko: '거주자 전용', zh: '仅居民', fr: 'Résidents seulement', es: 'Solo residentes' },
  '39':  { ru: 'Семейный комбо', en: 'Family combo', vi: 'Combo gia đình', ko: '패밀리 콤보', zh: '家庭套餐', fr: 'Combo famille', es: 'Combo familiar' },
  '40':  { ru: 'За отзыв (Google Maps)', en: 'Google Maps review', vi: 'Đánh giá Google Maps', ko: '구글맵 리뷰', zh: '谷歌地图评价', fr: 'Avis Google Maps', es: 'Reseña Google Maps' },
  '41':  { ru: 'За чекин', en: 'For check-in', vi: 'Khi check-in', ko: '체크인 시', zh: '打卡优惠', fr: 'Pour un check-in', es: 'Por check-in' },
  '42':  { ru: 'При предзаказе', en: 'Pre-order', vi: 'Đặt trước', ko: '사전 주문 시', zh: '预订优惠', fr: 'En pré-commande', es: 'Al reservar' },
  '43':  { ru: 'Месяц дня рождения', en: 'Birthday month', vi: 'Tháng sinh nhật', ko: '생일 달', zh: '生日当月', fr: 'Mois d\'anniversaire', es: 'Mes de cumpleaños' },
  '44':  { ru: 'В день годовщины', en: 'Anniversary day', vi: 'Ngày kỷ niệm', ko: '기념일', zh: '周年纪念日', fr: 'Jour d\'anniversaire', es: 'Día de aniversario' },
  '45':  { ru: 'Для экспатов', en: 'Expats only', vi: 'Chỉ người nước ngoài', ko: '외국인 전용', zh: '仅外籍人士', fr: 'Expatriés seulement', es: 'Solo expatriados' },
  '46':  { ru: 'В непиковые часы', en: 'Off-peak hours', vi: 'Giờ thấp điểm', ko: '비수기 시간', zh: '非高峰时段', fr: 'Heures creuses', es: 'Horas valle' },
  '47':  { ru: 'Со своим стаканом', en: 'Bring your own cup', vi: 'Mang ly của bạn', ko: '텀블러 지참 시', zh: '自带杯', fr: 'Apportez votre tasse', es: 'Trae tu propio vaso' },
  '48':  { ru: 'Комбо-сеты', en: 'Combo sets', vi: 'Combo set', ko: '콤보 세트', zh: '套餐组合', fr: 'Combos', es: 'Sets combinados' },
  '49':  { ru: 'Оплата по QR', en: 'QR payment', vi: 'Thanh toán QR', ko: 'QR 결제 시', zh: 'QR支付', fr: 'Paiement par QR', es: 'Pago por QR' },
  '50':  { ru: 'Повторный визит', en: 'Return visit', vi: 'Lần ghé thăm tiếp theo', ko: '재방문 시', zh: '再次光临', fr: 'Visite de retour', es: 'Visita de regreso' },
};

const SERVICE_DISCOUNT_CODES_I18N = {
  '200': { ru: 'Скидка на первое посещение', en: 'First visit discount', vi: 'Giảm giá lần đầu', ko: '첫 방문 할인', zh: '首次访问折扣', fr: 'Remise première visite', es: 'Descuento primera visita' },
  '201': { ru: 'Первый урок бесплатно', en: 'First lesson for free', vi: 'Bài học đầu tiên miễn phí', ko: '첫 수업 무료', zh: '首课免费', fr: 'Premier cours gratuit', es: 'Primera clase gratis' },
  '202': { ru: 'Скидка на групповые занятия', en: 'Group class discount', vi: 'Giảm giá nhóm', ko: '그룹 수업 할인', zh: '团体课折扣', fr: 'Remise cours collectif', es: 'Descuento clases grupales' },
  '203': { ru: 'Бесплатная доставка', en: 'Free delivery', vi: 'Giao hàng miễn phí', ko: '무료 배송', zh: '免费送货', fr: 'Livraison gratuite', es: 'Envío gratis' },
  '204': { ru: 'Приведи друга (скидка обоим)', en: 'Bring a friend (both get discount)', vi: 'Mời bạn bè (cả hai đều được giảm)', ko: '친구 초대 (둘 다 할인)', zh: '推荐朋友（双方均享折扣）', fr: 'Parrainez un ami (remise pour les deux)', es: 'Trae un amigo (descuento para ambos)' },
  '205': { ru: 'Раннее бронирование', en: 'Early booking', vi: 'Đặt trước sớm', ko: '조기 예약 할인', zh: '早鸟预订', fr: 'Réservation anticipée', es: 'Reserva anticipada' },
  '206': { ru: 'Скидка за отзыв с фото', en: 'Discount for review with photo', vi: 'Giảm giá khi để lại nhận xét kèm ảnh', ko: '포토 리뷰 할인', zh: '带图好评折扣', fr: 'Remise pour avis avec photo', es: 'Descuento por reseña con foto' },
  '211': { ru: 'Скидка за отметку в сторис', en: 'Discount for story tag', vi: 'Giảm giá khi tag story', ko: '스토리 태그 할인', zh: '标记故事折扣', fr: 'Remise pour tag en story', es: 'Descuento por etiqueta en story' },
  '212': { ru: 'Консультация / диагностика бесплатно', en: 'Free consultation / diagnosis', vi: 'Tư vấn / chẩn đoán miễn phí', ko: '무료 상담 / 진단', zh: '免费咨询 / 诊断', fr: 'Consultation / diagnostic gratuit', es: 'Consulta / diagnóstico gratis' },
  '213': { ru: 'Счастливые часы в будни', en: 'Happy hours on weekdays', vi: 'Giờ vàng ngày thường', ko: '평일 해пи아워', zh: '工作日欢乐时光', fr: 'Happy hours en semaine', es: 'Happy hours en semana' },
  '207': { ru: 'Подарок к заказу', en: 'Gift with order', vi: 'Quà tặng kèm theo', ko: '주문 시 선물 증정', zh: '下单赠礼', fr: 'Cadeau avec commande', es: 'Regalo con pedido' },
  '208': { ru: 'Пакет услуг (от 3-х)', en: 'Service package (3+)', vi: 'Gói dịch vụ (từ 3 gói)', ko: '서비스 패키지 (3개 이상)', zh: '服务套餐（3个起）', fr: 'Forfait services (3+)', es: 'Paquete de servicios (3+)' },
  '210': { ru: 'Специальное предложение', en: 'Special offer', vi: 'Ưu đãi đặc biệt', ko: '특별 제공', zh: '特别优惠', fr: 'Offre spéciale', es: 'Oferta especial' },
};

export function getDiscountCodes(lang = 'ru', mode = 'places') {
  const codes = mode === 'services' ? SERVICE_DISCOUNT_CODES_I18N : DISCOUNT_CODES_I18N;
  return Object.entries(codes).map(([code, texts]) => ({
    code,
    text: texts[lang] || texts['ru'],
  }));
}

export default DISCOUNT_CODES_I18N;
